### ISSUE TITLE
[TESTPLAN] Full Test Plan for 1.0/GA for RootAdmin, VMware 65, ACS 4.14.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack-primate#516]
Note: for User role test exclude after Account/User feature, for DomainAdmin role exclude after Infrastructure (except for Offerings)

**Common**
- [x] Project selector
- [x] Language selector
- [x] Notifications / clear notifications
- [ ] Paginations - #528
- [x] Profile
- [x] Help
- [x] Logout
- [ ] Context-sensitive help  - #528

**Dashboard**
- [x] Fetch latest
- [x] View hosts in alert state
- [x] View alerts
- [x] View events

**Compute > Instances**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Filter by
- [x] Create new instance

**Compute > Kubernetes**
- [ ] Basic search
- [ ] Extended search
- [ ] Sort
- [ ] Links
- [ ] Filter by
- [ ] Add Kubernetes cluster
- [ ] Start/stop a Kubernetes cluster
- [ ] Scale Kubernetes cluster
- [ ] Upgrade Kubernetes cluster
- [ ] Delete Kubernetes cluster

**Compute > Instances > selected instance**
- [x] View console
- [x] Reboot instance
- [x] Update instance
- [x] Start/Stop instance
- [x] Reinstall instance
- [x] Take snapshot
- [x] Assign VM to backup offering
- [x] Attach ISO
- [x] Scale VM
- [x] Migrate instance to another host
- [x] Change affinity
- [x] Change service offering
- [x] Reset Instance Password
- [x] Assign Instance to Another Account
- [x] Network adapters
- [x] 	- Add network to VM
- [x] 	- Set default NIC
- [x] 	- Add/delete secondary IP address
- [x] 	- Delete VM network
- [x] Settings
- [x] 	- Add setting
- [x] 	- Update setting
- [x] 	- Delete setting
- [x] Add / delete comment
- [x] Add / delete tags
- [x] Links

**Compute > Instance groups**
- [x] Search
- [x] Sort
- [x] Links
- [x] New instance group

**Compute > Instance groups > selected instance group**
- [x] Links
- [x] Update instance group
- [x] Delete instance group

**Compute > SSH Key Pairs**
- [x] Search
- [x] Sorting
- [ ] Links  - #528
- [x] New SSH key pair

**Compute > SSH Key Pairs > selected SSH key pair**
- [ ] Links  - #528
- [x] Delete SSH key pair

**Compute > Affinity Groups**
- [x] Search
- [x] Sort
- [x] Links
- [x] New affinity group

**Compute > Affinity Groups > selected affinity group**
- [x] Links
- [x] Delete affinity group

**Storage > Volumes**
- [x] Basic earch
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Create volume
- [x] Upload local volume
- [x] Upload volume from URL

**Storage > Volumes > selected volume**
- [x] Detach volume
- [x] Take snapshot
- [x] Recurring snapshot
- [x] Resize volume
- [x] Migrate volume
- [x] Download volume
- [x] Delete volume
- [x] Links
- [x] Add/delete tags

**Storage > Snapshots**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links

**Storage > Snapshots > selected snapshot**
- [x] Links
- [x] Add/delete tags
- [x] Create template
- [x] Create volume
- [x] Revert snapshot
- [x] Delete snapshot

**Storage > VM Snapshots**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [ ] Links  - #528

**Storage > VM Snapshots > selected snapshot**
- [x] Links
- [x] Add/delete tags
- [x] Revert VM snapshot
- [x] Delete VM snapshot

**Storage > Backups**
- [x] Import offering
- [ ] Configure backup provider (Veeam)
- [x] Create backup offering
- [x] Assign VM to backup offering
- [x] Revert to backup
- [x] Delete backup

**Network > Guest networks**
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Links
- [x] Add network

**Network > Guest networks > selected network**
- [ ] Links  - #528
- [ ] Add/delete tags  - #528
- [x] Update network
- [x] Restart network
- [x] Delete network
- [x] Acquire new IP (only for isolated networks)
- [x] Replace ACL list(only for isolated networks)
- [x] Delete public IP address (only for isolated networks)
- [x] Add/delete egress rule (only for isolated networks)
- [ ] Add/delete egress tags (only for isolated networks)

**Network > VPC **
- [x] Basic search
- [x] Extended search
- [x] Sort
- [ ] Links  - #528
- [x] Add VPC

**Network > VPC > selected VPC**
- [ ] Links  - #528
- [x] Update VPC
- [x] Restart VPC
- [x] Delete VPC
- [x] Networks
- [x] - Links
- [ ] - Paginations
- [x] - Add network
- [x] - Add internal LB
- [x] Public IP addresses
- [x] - Links
- [x] - Pagination
- [x] - Select tier
- [x] - Acquire new IP
- [x] - Delete IP address
- [x] Network ACL Lists
- [x] - Links
- [ ] - Pagination  - #528
- [x] - Add network ACL list
- [x] Private Gateways
- [ ] - Links  - #528
- [x] - Pagination
- [x] - Add private gateway
- [x] VPN Gateway
- [ ] - Links
- [ ] VPN Connections
- [x] - Links
- [ ] - Pagination
- [x] - Create Site-to-site VPN connection
- [x] Virtual routers
- [x] - Links
- [x] Add/delete tags

**Network > Security groups**
- [x] Search
- [x] Sort
- [x] Links
- [x] Add security group

**Network > Security groups > selected security group**
- [x] Links
- [x] Add/delete tags
- [x] Add ingress rule by CIDR
- [x] Add ingress rule by Account
- [x] Ingress rule - add/delete tags
- [x] Ingress rule - delete
- [x] Add egress rule by CIDR
- [x] Add egress rule by Account
- [x] Egress rule - add/delete tags
- [x] Egress rule - delete
- [ ] Ingress/egress rules pagination  - #528

**Network > Public IP Addresses**
- [x] Search
- [x] Sort
- [x] Links
- [x] Acquire new IP

**Network > Public IP Addresses > selected IP address**
- [x] Links
- [x] Add/delete tags
- [x] Enable/Disable static NAT
- [x] Release IP
- [x] Firewall - add rule
- [x] Firewall rule - add/delete tags
- [x] Firewall rule - delete
- [x] VPN - Enable/Disable VPN
- [x] VPN - Manage VPN Users

**Network > VPN Users**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add VPN user

**Network > VPN Users > selected VPN user**
- [x] Links
- [x] Delete VPN User

**Network > VPN Customer Gateway**
- [ ] Links  - #528
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Add VPN Customer Gateway

**Network > VPN Customer Gateway > selected gateway**
- [ ] Links  - #528
- [x] Edit VPN Customer Gateway
- [x] Delete VPN Customer Gateway
- [x] Add/delete tags

**Images > Templates**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Change order (move to the top/bottom, move one row up/down)
- [x] Register template
- [x] Upload local template

**Images > Templates > selected template**
- [x] Links
- [x] Add/delete tags
- [x] Edit template
- [x] Copy template
- [x] Update template permissions
- [x] Delete template
- [x] Download template
- [x] Zones pagination
- [ ] Settings - add/edit/remove setting - #528

**Images > ISOs**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [ ] Change order (move to the top/bottom, move one row up/down) : Icons exists but is it supported ? Not via API but does it actually work ?
- [x] Register ISO
- [x] Upload local ISO

**Images > ISOs > selected ISO**
- [x] Links
- [x] Add/delete tags
- [x] Edit ISO
- [x] Download ISO
- [x] Update ISO permissions
- [x] Copy ISO
- [x] Delete ISO
- [x] Zones - pagination

**Images > Kubernetes ISOs**
- [ ] Links
- [ ] Basic search
- [ ] Sort
- [ ] Refresh
- [ ] Pagination
- [ ] Enable/Disable
- [ ] Add Kubernetes Version

**Projects**
- [x] Links
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Switch to project
- [x] New project
- [x] Enter token
- [x] Project invitations

**Projects > selected project**
- [x] Links
- [x] Add/delete tags
- [x] Edit project
- [x] Suspend/Activate project
- [x] Add account to project
- [x] Accounts - Make account project owner
- [x] Accounts - Remove account from project
- [x] Delete project
- [x] Accounts - pagination
- [x] Resources - edit

**Events**
- [ ] Links - #528
- [x] Basic search
- [x] Extended search
- [x] Sort
- [x] Archive event
- [x] Delete event

**Events > selected event**
- [x] Links
- [x] Archive event
- [x] View event timeline
- [x] Delete event

**Users**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add user

**Accounts**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add account
- [ ] Add LDAP account

**Accounts > selected account**
- [x] Links
- [x] Update account
- [x] Update resource count
- [x] Disable/enable account
- [x] Lock/unlock account
- [x] Add certificate
- [x] Delete account
- [x] Settings

**Users > selected user**
- [x] Links
- [x] Edit user
- [x] Change password
- [x] Generate keys
- [x] Disable/enable user
- [x] Delete user
- [x] Copy API Key
- [x] Copy Secret Key

**Domains**
- [x] Search
- [x] Expand/collapse
- [x] Add/delete note
- [x] Add domain
- [x] Edit domain
- [x] Delete domain
- [x] Update resource count
- [ ] Link domain to LDAP Group/OU
- [x] Settings

**Roles**
- [x] Links
- [x] Search
- [x] Sort
- [x] Create role

**Roles > selected role**
- [x] Edit role
- [x] Delete role
- [x] Rules - add new rule
- [x] Rules - modify rule
- [x] Rules - delete rule
- [x] Rules - change rules order

**Infrastructure > Summary**
- [x] Links
- [ ] Setup SSL certificate - Missing contextual help  - #528

**Infrastructure > Zones**
- [x] Links
- [x] Search
- [x] Sort
- [x] Pagination
- [x] Add zone

**Infrastructure > Zones > selected zone**
- [x] Links
- [x] Edit zone
- [x] Enable/disable zone
- [x] Enable/disable out-of-band management
- [x] Enable HA (disable?)
- [x] Add VMWare datacenter
- [x] Delete zone
- [x] Settings - edit

**Infrastructure > Pods**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add Pod

**Infrastructure > Pods > selected Pod**
- [x] Links
- [x] Dedicate/Release Pod
- [x] Edit Pod
- [x] Disable/enable Pod
- [x] Delete Pod

**Infrastructure > Clusters**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add Cluster

**Infrastructure > Clusters > selected cluster**
- [x] Links
- [x] Dedicate/Release cluster
- [x] Enable/disable cluster
- [x] Manage/unmanage cluster
- [x] Enable/disable out-of-band management
- [x] Enable/disable HA
- [x] Configure HA
- [x] Delete cluster
- [x] Settings - edit

**Infrastructure > Hosts**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add host

**Infrastructure > Hosts > selected host**
- [x] Links
- [x] Add/delete notes
- [x] Dedicate/release host
- [x] Edit host
- [x] Force reconnect
- [x] Disable/enable host
- [x] Enable/cancel maintenance mode
- [x] Enable/disable out-of-band management
- [x] Enable/disale HA
- [x] Delete host (only if disabled)

**Infrastructure > Primary Storage**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add Primary storage

**Infrastructure > Primary Storage > selected primary storage**
- [x] Links
- [x] Edit primary storage
- [x] Enable/cancel maintenance mode
- [x] Delete primary storage
- [x] Settings - edit

**Infrastructure > Secondary Storage**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add Secondary storage

**Infrastructure > Secondary Storage > selected secondary storage**
- [x] Links
- [x] Delete secondary storage
- [x] Settings - edit

**Infrastructure > System VMs**
- [x] Links
- [x] Search
- [x] Sort

**Infrastructure > System VMs > selected system VM**
- [x] Links
- [x] View console
- [x] Start/Stop system VM
- [x] Reboot system VM
- [x] Change service offering
- [x] Migrate system VM
- [x] Run diagnostics
- [x] Get diagnostics data
- [x] Destroy system VM

**Infrastructure > Virtual routers**
- [x] Links
- [x] Search
- [x] Sort

**Infrastructure > Virtual routers > selected virtual router**
- [ ] Links  - #528
- [x] View console (running)
- [x] Start/Stop router
- [x] Reboot router
- [x] Change service offering
- [x] Migrate router (running)
- [x] Run diagnostics (running)
- [x] Get diagnostics data
- [x] Destroy router

**Infrastructure > Internal LB VMs**
- [x] Links
- [x] Search
- [x] Sort

**Infrastructure > Internal LB VMs > selected internal LB VM**
- [x] Links
- [x] View console
- [x] Stop router
- [x] Migrate router

**Infrastructure > CPU Sockets**
~- [ ] Search~ Not present and Not supported via backend
- [x] Sort

**Infrastructure > Management servers**
- [x] Links
~- [ ] Search~ Not supported via backend
- [ ] Sort

**Infrastructure > Management servers > selected management server**

**Infrastructure > Alerts**
- [x] Links
- [x] Search
- [x] Sort

**Infrastructure > Alerts > selected alert**
- [x] Archive alert
- [x] Delete alert

**Offerings > Compute offerings**
- [x] Links
- [x] Search
- [x] Sort
- [x] Add offering

**Offerings > Compute offerings > selected offering**
- [x] Links
- [x] Edit offering
- [x] Update offering access
- [x] Delete offering

**Offerings > System offerings**
- [x] Links
- [x] Search
- [x] Sort
- [x] Change order (move to the top/bottom, move one row up/down)
- [x] Add offering

**Offerings > System offerings > selected offering**
- [x] Edit offering
- [x] Delete offering

**Offerings > Disk offerings**
- [x] Links
- [x] Search
- [x] Sort
- [x] Change order (move to the top/bottom, move one row up/down)
- [x] Add offering

**Offerings > Disk offerings > selected offering**
- [x] Links
- [x] Edit offering
- [x] Update offering access
- [x] Delete offering

**Offerings > Backup offerings**

**Offerings > Network offerings**
- [x] Links
- [x] Search
- [x] Sort
- [x] Change order (move to the top/bottom, move one row up/down)
- [x] Add offering

**Offerings > Network offerings > selected offering**
- [x] Edit offering
- [x] Enable/Disable offering
- [x] Update offering access
- [x] Delete offering

**Offerings > VPC offerings**
- [x] Links
- [x] Search
- [x] Sort
- [x] Change order
- [x] Add offering

**Offerings > VPC offerings > selected offering**
- [x] Links
- [x] Add / delete tags
- [x] Edit offering
- [x] Enable/Disable offering
- [x] Update offering access
- [x] Delete offering

**Configuration > Global settings**
- [x] Links
- [x] Search
- [x] Sort
- [x] Edit value

**Configuration > LDAP Configuration**
- [x] Links
~- Search~ Not supported via backend
- [x] Sort
- [x] Configure LDAP

**Configuration > LDAP Configuration > selected LDAP configuration**
- [ ] TBD

**Configuration > Hypervisor capabilities**
- [x] Data
- [ ] Search - #523 
- [x] Sort

**Comment by davidjumani** [comment]
Bugs listed in#528
